spring.application.name=spring-bot-ai

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:3b
spring.ai.ollama.chat.options.temperature=0.7

spring.datasource.url=jdbc:postgresql://localhost:5433/spring_bot_ai
spring.datasource.username=springbot
spring.datasource.password=springbot123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true